# 單層感知器實作

## 載入套件

In [1]:
import tensorflow as tf
import input_data

mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


## 訓練資料

In [2]:
batch_xs, batch_ys = mnist.train.next_batch(5)

In [3]:
batch_xs

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [4]:
batch_xs.shape

(5, 784)

In [5]:
batch_xs[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [6]:
batch_ys

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [7]:
batch_ys[0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.])

## 測試資料

In [8]:
mnist.test.images

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [9]:
mnist.test.images.shape

(10000, 784)

In [10]:
mnist.test.labels

array([[ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [11]:
mnist.test.labels.shape

(10000, 10)

## 建立Computational Graph

In [12]:
x_ = tf.placeholder(tf.float32, [None, 784], name="x_")
y_ = tf.placeholder(tf.float32, [None, 10], name="y_")

W = tf.Variable(tf.zeros([784, 10]), name="W")
b = tf.Variable(tf.zeros([10]), name="b")
y = tf.nn.softmax(tf.matmul(x_, W) + b)

cross_entropy = -tf.reduce_sum(y_ * tf.log(y))

optimizer = tf.train.GradientDescentOptimizer(0.01)
trainer = optimizer.minimize(cross_entropy)

init = tf.initialize_all_variables()


## Session

In [13]:
sess = tf.Session()
sess.run(init)

## W

In [14]:
sess.run(W)

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [15]:
sess.run(W).shape

(784, 10)

## b

In [16]:
sess.run(b)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32)

In [17]:
sess.run(b).shape

(10,)

## matmul(x_,w)

In [18]:
result_matmul = sess.run(tf.matmul(x_, W),feed_dict={x_: batch_xs})

In [19]:
result_matmul

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [20]:
result_matmul.shape

(5, 10)

## matmul(x_,w)+b

In [21]:
result_matmul_add = sess.run(tf.matmul(x_, W)+b,feed_dict={x_: batch_xs})

In [22]:
result_matmul_add

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [23]:
result_matmul_add.shape

(5, 10)

## y

In [24]:
result_y = sess.run(y,feed_dict={x_: batch_xs})
result_y

array([[ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1]], dtype=float32)

In [25]:
result_y.shape

(5, 10)

## y_ * log(y)

In [26]:
result_y_logy = sess.run(y_ * tf.log(y) ,feed_dict={x_: batch_xs, y_:batch_ys})
result_y_logy

array([[-0.        , -0.        , -0.        , -0.        , -0.        ,
        -0.        , -0.        , -2.30258512, -0.        , -0.        ],
       [-0.        , -0.        , -0.        , -2.30258512, -0.        ,
        -0.        , -0.        , -0.        , -0.        , -0.        ],
       [-0.        , -0.        , -0.        , -0.        , -2.30258512,
        -0.        , -0.        , -0.        , -0.        , -0.        ],
       [-0.        , -0.        , -0.        , -0.        , -0.        ,
        -0.        , -2.30258512, -0.        , -0.        , -0.        ],
       [-0.        , -2.30258512, -0.        , -0.        , -0.        ,
        -0.        , -0.        , -0.        , -0.        , -0.        ]], dtype=float32)

In [27]:
result_y_logy.shape

(5, 10)

## Cross Entropy

In [28]:
result_cross_entropy = sess.run(cross_entropy  ,feed_dict={x_: batch_xs, y_:batch_ys})
result_cross_entropy

11.512926

## 建立成效評估用的Computational Graph

In [29]:
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

## Correct Prediction

In [30]:
result_correct_prediction = sess.run(correct_prediction, feed_dict={x_: batch_xs, y_: batch_ys})
result_correct_prediction

array([False, False, False, False, False], dtype=bool)

## Accurarcy

In [31]:
result_accurarcy = sess.run(accuracy, feed_dict={x_: batch_xs, y_: batch_ys})
result_accurarcy

0.0

## 訓練一次

In [32]:
sess.run(trainer,  feed_dict={x_: batch_xs, y_: batch_ys})

## Cross Entropy

In [33]:
result_cross_entropy_2 = sess.run(cross_entropy  ,feed_dict={x_: batch_xs, y_:batch_ys})
result_cross_entropy_2

8.636961

## Accurarcy

In [34]:
result_accurarcy_2 = sess.run(accuracy, feed_dict={x_: batch_xs, y_: batch_ys})
result_accurarcy_2

1.0

## 訓練1000次

In [35]:
for i in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(trainer,  feed_dict={x_: batch_xs, y_: batch_ys})
    if (i+1)%50 == 0:
        print "%s, %s" %(i+1, (sess.run(accuracy, feed_dict={x_: mnist.test.images, y_: mnist.test.labels})))

50, 0.8603
100, 0.8934
150, 0.857
200, 0.8986
250, 0.8962
300, 0.893
350, 0.896
400, 0.893
450, 0.9088
500, 0.8962
550, 0.9056
600, 0.9146
650, 0.9161
700, 0.9185
750, 0.9112
800, 0.9145
850, 0.9143
900, 0.9089
950, 0.9137
1000, 0.9153


## 儲存模型

In [36]:
import json

In [37]:
f = open("model1.json","w")

In [38]:
result_W = sess.run(W)
result_b = sess.run(b)

In [39]:
result_b

array([ -5.92038870e-01,   3.84339869e-01,   2.41273135e-01,
        -2.97503620e-01,  -1.80803635e-03,   1.96461451e+00,
        -1.54077470e-01,   9.35569167e-01,  -2.06071424e+00,
        -4.19651836e-01], dtype=float32)

In [40]:
result_b.tolist()

[-0.5920388698577881,
 0.3843398690223694,
 0.24127313494682312,
 -0.29750362038612366,
 -0.0018080363515764475,
 1.9646145105361938,
 -0.1540774703025818,
 0.935569167137146,
 -2.0607142448425293,
 -0.4196518361568451]

In [41]:
json_to_write = json.dumps({
        "W": result_W.tolist(),
        "b": result_b.tolist(),
    },indent=4)
f.write(json_to_write)
f.close()